name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BINARY_NAME: phdb_create_images_zip
      FUNCTION_NAME: phdb_create_images_zip
    steps:
      - uses: actions/checkout@v2
      - name: Build and Zip
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl
      - run: |
          sudo mv ./target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }} ./bootstrap
          sudo chmod 755 ./bootstrap  
          zip lambda.zip ./bootstrap
      - name: Push to aws/lambda
        uses: stcalica/update-lambda@master
        with:
          package: lambda.zip
          function-name: ${{ env.FUNCTION_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
